name: package
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20
          cache: true
          check-latest: true
      - uses: sigstore/cosign-installer@v3.4.0
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token:  ${{ secrets.GITHUB_TOKEN }}
      - uses: anchore/sbom-action/download-syft@v0.15.8
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        name: ghcr.io login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        name: docker.io login
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
      - run: |
          echo "$NFPM_GPG_KEY" > ${{ runner.temp }}/gpg.key
        env:
          NFPM_GPG_KEY: ${{ secrets.AMIKOS_OSS_GPG_SECRET_KEY }}
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.gh_pat }}
          GPG_KEY_PATH: ${{ runner.temp }}/gpg.key
          NFPM_DEFAULT_PASSPHRASE: ${{ secrets.AMIKOS_OSS_GPG_SECRET_KEY_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          name: dist
          path: |
            dist

  
